[package]
name = "a_tree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "a_tree"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
a-tree = "0.5.1"
mimalloc = "0.1.43"
rustler = "0.37"
